server:
  port: 8088
spring:
  resources:
    static-locations: classpath:/templates/,classpath:/static/
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/resources
  thymeleaf:
    cache: false
    mode: LEGACYHTML5